
#type: args

train:
  epochs: 600
  batch_size: 16
  lr: 1.0e-3

diffusion:
  layers: 4
  channels: 64
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  time_layer:
    type: "bilstm"
    nheads: 8
    hidden_size: 64
    attention_window: 5
  spatial_layer:
    type: 'None'
    nheads: 8
    hidden_size: 64
    adj: './data/adj_matrix.npy'
    order: 2

model:
  is_unconditional: 0
  timeemb: 32
  featureemb: 16
  target_strategy: "random"
  missing_pattern: "space_block"
